# ===================================================================
# CONFIGURACIoN DEL SERVIDOR
# ===================================================================
server.port=8080
server.servlet.context-path=/api/v1

# ===================================================================
# CONFIGURACIoN DE LA BASE DE DATOS (MySQL en Docker)
# ===================================================================
# localhost funciona si corres Spring Boot de forma nativa/IDE y la BD en Docker.
# Si metes la app de Spring Boot a Docker mas adelante, cambiaras 'localhost' por 'mysql-db'.
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACIoN DE JPA / HIBERNATE
# ===================================================================
# 'update' sincroniza el modelo de entidades Java con las tablas de la BD en cada inicio.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logs de SQL para depuracion en desarrollo (puedes pasarlo a false en produccion)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURACIoN DE FORMATOS Y TIEMPO (Crucial para los Timestamps)
# ===================================================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Santiago

# ===================================================================
# LiMITES DE CARGA DE ARCHIVOS (Por si en el futuro subes fotos de los activos)
# ===================================================================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB


# ==========================================
# CONFIGURACIoN DE SWAGGER (OPENAPI)
# ==========================================

# 1. Cambia la ruta de la interfaz visual (UI) a algo mas corto, como "/docs"
springdoc.swagger-ui.path=/docs

# 2. Cambia la ruta donde se genera el JSON puro del contrato (Opcional)
springdoc.api-docs.path=/api-docs

# 3. Ordena los endpoints alfabeticamente en la pantalla (Muy util cuando la API crece)
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# 4. Desactiva Swagger en produccion (Por seguridad, si alguna vez subes esto a un servidor publico)
# springdoc.api-docs.enabled=false
